/**
 * @license
 * Copyright LOGO YAZILIM SANAYİ VE TİCARET A.Ş. All Rights Reserved.
 *
 * Save to the extent permitted by law, you may not use, copy, modify,
 * distribute or create derivative works of this material or any part
 * of it without the prior written consent of LOGO YAZILIM SANAYİ VE TİCARET A.Ş. Limited.
 * Any reproduction of this material must contain this notice.
 */

// IMPORTANT: THIS TS FILE IS AUTO GENERATED! DO NOT MANUALLY EDIT OR CHECKIN!
export const LOGO_ICONS = [
  'add-new',
  'add',
  'arrow-down',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'ayna-doc',
  'ayna-folder',
  'ayna-upload',
  'bin',
  'browse',
  'chart',
  'copy',
  'date',
  'doc',
  'double-chevron-down',
  'double-chevron-left',
  'double-chevron-right',
  'double-chevron-up',
  'drag',
  'edit-pen',
  'edit',
  'email',
  'enveloppe-open',
  'eye',
  'eyedropper',
  'file',
  'filter',
  'ghost',
  'group',
  'hamburger-fill',
  'hamburger',
  'home-fill',
  'large-0',
  'large-chevron-down',
  'large-chevron-left',
  'large-chevron-right',
  'large-chevron-up',
  'large-ghost',
  'large',
  'link',
  'menu-left-alt',
  'minus',
  'new',
  'org',
  'paas-checked',
  'person',
  'print',
  'refresh',
  'remove',
  'right-one',
  'right',
  'search',
  'selection',
  'share',
  'small-check',
  'small-chevron-down',
  'small-chevron-left',
  'small-chevron-up',
  'small-cross',
  'star',
  'tab-settings',
  'table-refresh',
  'three-dots-ver',
  'tiny-chevron-down',
  'tiny-chevron-left',
  'tiny-chevron-right',
  'warning'
];
