/**
 * @license
 * Copyright LOGO YAZILIM SANAYİ VE TİCARET A.Ş. All Rights Reserved.
 *
 * Save to the extent permitted by law, you may not use, copy, modify,
 * distribute or create derivative works of this material or any part
 * of it without the prior written consent of LOGO YAZILIM SANAYİ VE TİCARET A.Ş. Limited.
 * Any reproduction of this material must contain this notice.
 */

// IMPORTANT: THIS TS FILE IS AUTO GENERATED! DO NOT MANUALLY EDIT OR CHECKIN!
export const LOGO_ICONS = [
  'add-new',
  'add',
  'asc-alphabet',
  'asc-number',
  'bin',
  'bold-g',
  'browse',
  'cal-view-glyph',
  'copy',
  'date',
  'des-alphabet',
  'des-number',
  'doc-g',
  'double-large-chevron-down',
  'double-large-chevron-left',
  'double-large-chevron-right',
  'double-large-chevron-up',
  'drag',
  'edit-pen',
  'edit',
  'email',
  'eye',
  'eyedropper',
  'file-g',
  'filter',
  'group',
  'hamburger-g',
  'hamburger',
  'home-g',
  'icon-list-glyph',
  'icon-list',
  'info',
  'italic-g',
  'large-chevron-down',
  'large-chevron-left',
  'large-chevron-right',
  'large-chevron-up',
  'link',
  'list',
  'lock-g',
  'logo-org',
  'logo-refresh',
  'logo-zoom-in',
  'mobile-back',
  'new',
  'paas-checked',
  'people',
  'person',
  'print',
  'remove',
  'row-list-glyph',
  'save',
  'saved-offline-glyph',
  'search-filter',
  'search-g',
  'search',
  'selection-dropdown',
  'settings',
  'share',
  'shared-g',
  'small-check',
  'small-chevron-down',
  'small-chevron-left',
  'small-chevron-right',
  'small-chevron-up',
  'small-cross',
  'tab-settings',
  'table-refresh',
  'tasked-glyph',
  'three-dots-ver',
  'underlined-g',
  'warning',
  'zoom-out'
];
